- name: Apply common configurations
  hosts: all
  become: yes
  roles:
    - common

- name: Configure Kubernetes master node
  hosts: masters
  become: yes
  roles:
    - master

- name: Configure Kubernetes worker nodes
  hosts: nodes
  become: yes
  roles:
    - nodes
