- name: Disable swap
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swap entry from /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^\s*([^#\s]+\s+){2}swap\s+'
    replace: '# \g<0>'
  when: ansible_swaptotal_mb > 0
